### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by riley-9054** [FionaTheMortal/Better-Biome-Blend#71]
This has already been reported three times, it is no different from the previous ones. I am reporting it again because the owner of this mod is either lazy or dead, because they've clearly not made any statements or actions to show that the mod is either abandoned or that it is under maintenance.

**Comment by riley-9054** [comment]
tl;dr: Either update it or say that it's not getting updated already.

**Comment by Nekkowe** [comment]
Yeah, having the same issue, it's not working at all

> [13:39:07] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: betterbiomeblend, class fionathemortal.betterbiomeblend.BetterBiomeBlend
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23257!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23256!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {re:mixin}
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ScreenEvent$InitScreenEvent$Post
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3434) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetPublicMethods(Class.java:3459) ~[?:?] {re:mixin}
	at java.lang.Class.getMethods(Class.java:2051) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%23106!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%23106!/:?] {}
	at fionathemortal.betterbiomeblend.BetterBiomeBlend.lambda$new$3(BetterBiomeBlend.java:31) ~[betterbiomeblend-1.19.0-1.3.6-forge.jar%23194!/:1.19-1.3.6-forge] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.2-43.2.0.jar%23256!/:?] {}
	at fionathemortal.betterbiomeblend.BetterBiomeBlend.<init>(BetterBiomeBlend.java:26) ~[betterbiomeblend-1.19.0-1.3.6-forge.jar%23194!/:1.19-1.3.6-forge] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ScreenEvent$InitScreenEvent$Post
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3434) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetPublicMethods(Class.java:3459) ~[?:?] {re:mixin}
	at java.lang.Class.getMethods(Class.java:2051) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%23106!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%23106!/:?] {}
	at fionathemortal.betterbiomeblend.BetterBiomeBlend.lambda$new$3(BetterBiomeBlend.java:31) ~[betterbiomeblend-1.19.0-1.3.6-forge.jar%23194!/:1.19-1.3.6-forge] {re:classloading}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.19.2-43.2.0.jar%23256!/:?] {}
	at fionathemortal.betterbiomeblend.BetterBiomeBlend.<init>(BetterBiomeBlend.java:26) ~[betterbiomeblend-1.19.0-1.3.6-forge.jar%23194!/:1.19-1.3.6-forge] {re:classloading}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?] {}
	... 11 more
